ZURICH_TREES:
        path: './module/zurich-baeume/baumkataster.json'
        key: 'features'
        latitude: ['geometry', 'coordinates', 1]
        longitude: ['geometry', 'coordinates', 0]
        features:
                year: ['properties', 'pflanzjahr']
        filter:
                year: 1970

BERLIN_WALL:
        path: './module/berlin/berlin_wall.geojson'

BERLIN_HISTORIC:
        path: './module/berlin/historic_sites.geojson'
        key: 'features'
        latitude: ['geometry', 'coordinates', 1]
        longitude: ['geometry', 'coordinates', 0]
        features:
                name: ['properties', 'name']

TEST:
        path: './module/test/poi.geojson'
        key: 'features'
        latitude: ['geometry', 'coordinates', 1]
        longitude: ['geometry', 'coordinates', 0]
        features:
                name: ['properties', 'name']
